name: Deploy Databricks Notebook

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0  # Specify the Terraform version you want to use

      - name: Create Terraform Configuration
        run: |
          echo 'terraform {
            required_providers {
              databricks = {
                source  = "databricks/databricks"
                version = "1.4.0"
              }
            }
          }' > main.tf

          echo 'provider "databricks" {
            host  = "${{ secrets.DATABRICKS_HOST }}"
            token = "${{ secrets.DATABRICKS_TOKEN }}"
          }' >> main.tf

          echo 'variable "databricks_host" {
            description = "The Databricks workspace URL"
            type        = string
          }' >> main.tf

          echo 'variable "databricks_token" {
            description = "The Databricks personal access token"
            type        = string
          }' >> main.tf

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform Deployment
        run: terraform plan -out=tfplan -input=false

      - name: Apply Terraform Deployment
        run: terraform apply -auto-approve tfplan
