name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0  # Specify the Terraform version you want to use

      - name: Terraform Init
        run: terraform init
        working-directory: cluster_creation/notebook_creation_db  # Adjusted path based on your directory structure

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: cluster_creation/notebook_creation_db  # Ensure this points to your .tf files

      - name: Terraform Validate
        run: terraform validate
        working-directory: cluster_creation/notebook_creation_db  # Validate the configuration files

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false
        working-directory: cluster_creation/notebook_creation_db  # Ensure this points to your .tf files

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: cluster_creation/notebook_creation_db  # Ensure this points to your .tf files
